"""schedule and lessons t3 01

Revision ID: a3b1c0d4e5f6
Revises: fddb2f6cef06
Create Date: 2026-10-07 09:19:54.784066+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "a3b1c0d4e5f6"
down_revision: str | None = "fddb2f6cef06"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Нужно для EXCLUDE USING gist по teacher_id (создано и первой ревизией; повтор безопасен).
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")
    """Прямое применение миграции."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "schedule_templates",
        sa.Column(
            "id",
            sa.BIGINT(),
            sa.Identity(always=True),
            nullable=False,
            comment="PK, BIGINT IDENTITY",
        ),
        sa.Column(
            "teacher_id", sa.BIGINT(), nullable=False, comment="Преподаватель; FK → users, RESTRICT"
        ),
        sa.Column(
            "subject_id", sa.BIGINT(), nullable=False, comment="Предмет; FK → subjects, RESTRICT"
        ),
        sa.Column(
            "weekday",
            sa.SmallInteger(),
            nullable=False,
            comment="День недели ISO: 1 = понедельник … 7 = воскресенье",
        ),
        sa.Column(
            "start_local_time",
            sa.Time(),
            nullable=False,
            comment="Локальное время начала (в поясе timezone)",
        ),
        sa.Column(
            "duration_minutes",
            sa.SmallInteger(),
            server_default=sa.text("60"),
            nullable=False,
            comment="Длительность в минутах, CHECK > 0; по умолчанию 60",
        ),
        sa.Column(
            "timezone",
            sa.VARCHAR(length=64),
            nullable=False,
            comment="IANA-пояс, в котором задано start_local_time",
        ),
        sa.Column("starts_on", sa.Date(), nullable=False, comment="Первая дата серии"),
        sa.Column(
            "ends_on", sa.Date(), nullable=True, comment="Последняя дата серии; NULL — без конца"
        ),
        sa.Column(
            "is_active",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            nullable=False,
            comment="false = пауза/отключение шаблона",
        ),
        sa.Column(
            "generated_until",
            sa.Date(),
            nullable=True,
            comment="До какой даты уже сгенерированы уроки",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Время создания записи (TIMESTAMPTZ, UTC; docs/04 §0)",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Время последнего изменения; обновляется в приложении (docs/04 §0)",
        ),
        sa.CheckConstraint(
            "duration_minutes > 0", name=op.f("ck_schedule_templates_duration_positive")
        ),
        sa.CheckConstraint(
            "weekday BETWEEN 1 AND 7", name=op.f("ck_schedule_templates_weekday_range")
        ),
        sa.ForeignKeyConstraint(
            ["subject_id"],
            ["subjects.id"],
            name=op.f("fk_schedule_templates_subject_id"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["teacher_id"],
            ["users.id"],
            name=op.f("fk_schedule_templates_teacher_id"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_schedule_templates")),
    )
    op.create_table(
        "lessons",
        sa.Column(
            "id",
            sa.BIGINT(),
            sa.Identity(always=True),
            nullable=False,
            comment="PK, BIGINT IDENTITY",
        ),
        sa.Column(
            "teacher_id", sa.BIGINT(), nullable=False, comment="Кто проводит; FK → users, RESTRICT"
        ),
        sa.Column(
            "subject_id", sa.BIGINT(), nullable=False, comment="Предмет; FK → subjects, RESTRICT"
        ),
        sa.Column(
            "start_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Начало (TIMESTAMPTZ, UTC)",
        ),
        sa.Column(
            "end_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Конец (TIMESTAMPTZ, UTC), CHECK > start_at",
        ),
        sa.Column(
            "status",
            sa.VARCHAR(length=9),
            server_default=sa.text("'scheduled'"),
            nullable=False,
            comment="scheduled | completed | cancelled (VARCHAR+CHECK)",
        ),
        sa.Column(
            "template_id",
            sa.BIGINT(),
            nullable=True,
            comment="Из какого шаблона создан; при удалении шаблона — NULL",
        ),
        sa.Column(
            "is_detached",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            nullable=False,
            comment="true = изменён вручную, шаблон его не трогает",
        ),
        sa.Column(
            "video_url_override",
            sa.VARCHAR(length=500),
            nullable=True,
            comment="Переопределяет ссылку Телемоста из профиля",
        ),
        sa.Column(
            "board_url_override",
            sa.VARCHAR(length=500),
            nullable=True,
            comment="Переопределяет ссылку на доску из профиля",
        ),
        sa.Column("topic", sa.VARCHAR(length=255), nullable=True, comment="Тема занятия"),
        sa.Column(
            "teacher_note",
            sa.Text(),
            nullable=True,
            comment="Приватная заметка преподавателя (ученик не видит)",
        ),
        sa.Column(
            "completed_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Момент отметки «проведён»",
        ),
        sa.Column(
            "cancelled_at", sa.DateTime(timezone=True), nullable=True, comment="Момент отмены"
        ),
        sa.Column(
            "cancelled_by",
            sa.BIGINT(),
            nullable=True,
            comment="Кто отменил; при удалении аккаунта — NULL",
        ),
        sa.Column("cancel_reason", sa.VARCHAR(length=255), nullable=True, comment="Причина отмены"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Время создания записи (TIMESTAMPTZ, UTC; docs/04 §0)",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Время последнего изменения; обновляется в приложении (docs/04 §0)",
        ),
        postgresql.ExcludeConstraint(
            (sa.column("teacher_id"), "="),
            (sa.text("tstzrange(start_at, end_at)"), "&&"),
            where=sa.text("status <> 'cancelled'"),
            using="gist",
            name="ex_lessons_teacher_no_overlap",
        ),
        sa.CheckConstraint(
            "status IN ('scheduled', 'completed', 'cancelled')", name=op.f("ck_lessons_status")
        ),
        sa.CheckConstraint("end_at > start_at", name=op.f("ck_lessons_end_after_start")),
        sa.ForeignKeyConstraint(
            ["cancelled_by"],
            ["users.id"],
            name=op.f("fk_lessons_cancelled_by"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["subject_id"], ["subjects.id"], name=op.f("fk_lessons_subject_id"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["teacher_id"], ["users.id"], name=op.f("fk_lessons_teacher_id"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["schedule_templates.id"],
            name=op.f("fk_lessons_template_id"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lessons")),
        sa.UniqueConstraint(
            "template_id", "start_at", name=op.f("uq_lessons_template_id_start_at")
        ),
    )
    op.create_index("ix_lessons_start_at", "lessons", ["start_at"], unique=False)
    op.create_index("ix_lessons_status_start_at", "lessons", ["status", "start_at"], unique=False)
    op.create_index(
        "ix_lessons_teacher_id_start_at", "lessons", ["teacher_id", "start_at"], unique=False
    )
    op.create_table(
        "schedule_template_participants",
        sa.Column(
            "template_id",
            sa.BIGINT(),
            nullable=False,
            comment="FK → schedule_templates, ON DELETE CASCADE",
        ),
        sa.Column(
            "student_id", sa.BIGINT(), nullable=False, comment="Ученик; FK → users, RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["users.id"],
            name=op.f("fk_schedule_template_participants_student_id"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["schedule_templates.id"],
            name=op.f("fk_schedule_template_participants_template_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "template_id", "student_id", name=op.f("pk_schedule_template_participants")
        ),
    )
    op.create_table(
        "lesson_participants",
        sa.Column(
            "lesson_id", sa.BIGINT(), nullable=False, comment="FK → lessons, ON DELETE CASCADE"
        ),
        sa.Column(
            "student_id", sa.BIGINT(), nullable=False, comment="Ученик; FK → users, RESTRICT"
        ),
        sa.Column(
            "attendance",
            sa.VARCHAR(length=9),
            server_default=sa.text("'pending'"),
            nullable=False,
            comment="pending | attended | no_show | cancelled (VARCHAR+CHECK)",
        ),
        sa.Column(
            "is_billable",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            nullable=False,
            comment="Засчитывается в заработок",
        ),
        sa.Column(
            "price_snapshot",
            sa.Integer(),
            nullable=True,
            comment="Цена, зафиксированная при отметке (рубли), CHECK >= 0; видит только owner",
        ),
        sa.CheckConstraint(
            "attendance IN ('pending', 'attended', 'no_show', 'cancelled')",
            name=op.f("ck_lesson_participants_attendance"),
        ),
        sa.CheckConstraint(
            "price_snapshot >= 0", name=op.f("ck_lesson_participants_price_snapshot_nonneg")
        ),
        sa.ForeignKeyConstraint(
            ["lesson_id"],
            ["lessons.id"],
            name=op.f("fk_lesson_participants_lesson_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["users.id"],
            name=op.f("fk_lesson_participants_student_id"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("lesson_id", "student_id", name=op.f("pk_lesson_participants")),
    )
    op.create_index(
        "ix_lesson_participants_student_id_lesson_id",
        "lesson_participants",
        ["student_id", "lesson_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Откат миграции (удаляет всё, что создано в upgrade)."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_lesson_participants_student_id_lesson_id", table_name="lesson_participants")
    op.drop_table("lesson_participants")
    op.drop_table("schedule_template_participants")
    op.drop_index("ix_lessons_teacher_id_start_at", table_name="lessons")
    op.drop_index("ix_lessons_status_start_at", table_name="lessons")
    op.drop_index("ix_lessons_start_at", table_name="lessons")
    op.drop_table("lessons")
    op.drop_table("schedule_templates")
    # ### end Alembic commands ###
