"""catalog items t8 01

Revision ID: a8b9c0d1e2f3
Revises: f7a8b9c0d1e2
Create Date: 2026-10-08 13:23:12.622174+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "a8b9c0d1e2f3"
down_revision: str | None = "f7a8b9c0d1e2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Прямое применение миграции."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "catalog_items",
        sa.Column(
            "id",
            sa.BIGINT(),
            sa.Identity(always=True),
            nullable=False,
            comment="PK, BIGINT IDENTITY",
        ),
        sa.Column("title", sa.VARCHAR(length=150), nullable=False, comment="Название услуги"),
        sa.Column("description", sa.Text(), nullable=False, comment="Описание"),
        sa.Column(
            "price_text",
            sa.VARCHAR(length=100),
            nullable=True,
            comment="Стоимость свободным текстом, напр. «от 1500 ₽»",
        ),
        sa.Column(
            "sort_order",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
            comment="Порядок показа (меньше — выше)",
        ),
        sa.Column(
            "is_published",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            nullable=False,
            comment="Видна гостям и ученикам",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Время создания записи (TIMESTAMPTZ, UTC; docs/04 §0)",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Время последнего изменения; обновляется в приложении (docs/04 §0)",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_catalog_items")),
    )
    op.create_index(
        "ix_catalog_items_is_published_sort_order",
        "catalog_items",
        ["is_published", "sort_order"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Откат миграции (удаляет всё, что создано в upgrade)."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_catalog_items_is_published_sort_order", table_name="catalog_items")
    op.drop_table("catalog_items")
    # ### end Alembic commands ###
