"""homework t4 01

Revision ID: c4d2e5f7a8b9
Revises: a3b1c0d4e5f6
Create Date: 2026-10-07 12:58:17.800182+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "c4d2e5f7a8b9"
down_revision: str | None = "a3b1c0d4e5f6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Прямое применение миграции."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "homeworks",
        sa.Column(
            "id",
            sa.BIGINT(),
            sa.Identity(always=True),
            nullable=False,
            comment="PK, BIGINT IDENTITY",
        ),
        sa.Column(
            "created_by", sa.BIGINT(), nullable=False, comment="Кто создал; FK → users, RESTRICT"
        ),
        sa.Column(
            "lesson_id",
            sa.BIGINT(),
            nullable=True,
            comment="Урок, к которому привязано (необязательно); при удалении урока — NULL",
        ),
        sa.Column(
            "subject_id", sa.BIGINT(), nullable=False, comment="Предмет; FK → subjects, RESTRICT"
        ),
        sa.Column(
            "kind",
            sa.VARCHAR(length=9),
            nullable=False,
            comment="regular | mock_exam (VARCHAR+CHECK)",
        ),
        sa.Column(
            "exam_type_id",
            sa.BIGINT(),
            nullable=True,
            comment="Тип экзамена; обязателен для mock_exam; FK → exam_types, RESTRICT",
        ),
        sa.Column("title", sa.VARCHAR(length=200), nullable=False, comment="Название задания"),
        sa.Column("description", sa.Text(), nullable=True, comment="Инструкции к заданию"),
        sa.Column(
            "max_score",
            sa.SmallInteger(),
            nullable=False,
            comment="Макс. балл, CHECK > 0 (regular: число заданий)",
        ),
        sa.Column(
            "due_mode",
            sa.VARCHAR(length=11),
            nullable=False,
            comment="Как определён первоначальный дедлайн: next_lesson | fixed (VARCHAR+CHECK)",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Время создания записи (TIMESTAMPTZ, UTC; docs/04 §0)",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Время последнего изменения; обновляется в приложении (docs/04 §0)",
        ),
        sa.CheckConstraint(
            "due_mode IN ('next_lesson', 'fixed')", name=op.f("ck_homeworks_due_mode")
        ),
        sa.CheckConstraint(
            "kind <> 'mock_exam' OR exam_type_id IS NOT NULL",
            name=op.f("ck_homeworks_mock_exam_needs_exam_type"),
        ),
        sa.CheckConstraint("kind IN ('regular', 'mock_exam')", name=op.f("ck_homeworks_kind")),
        sa.CheckConstraint("max_score > 0", name=op.f("ck_homeworks_max_score_positive")),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_homeworks_created_by"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["exam_type_id"],
            ["exam_types.id"],
            name=op.f("fk_homeworks_exam_type_id"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["lesson_id"], ["lessons.id"], name=op.f("fk_homeworks_lesson_id"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["subject_id"],
            ["subjects.id"],
            name=op.f("fk_homeworks_subject_id"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_homeworks")),
    )
    op.create_table(
        "homework_assignments",
        sa.Column(
            "id",
            sa.BIGINT(),
            sa.Identity(always=True),
            nullable=False,
            comment="PK, BIGINT IDENTITY",
        ),
        sa.Column(
            "homework_id", sa.BIGINT(), nullable=False, comment="FK → homeworks, ON DELETE CASCADE"
        ),
        sa.Column(
            "student_id", sa.BIGINT(), nullable=False, comment="Ученик; FK → users, RESTRICT"
        ),
        sa.Column(
            "status",
            sa.VARCHAR(length=14),
            server_default=sa.text("'assigned'"),
            nullable=False,
            comment="assigned | submitted | needs_revision | graded | expired (VARCHAR+CHECK)",
        ),
        sa.Column(
            "original_due_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Первоначальный дедлайн (TIMESTAMPTZ)",
        ),
        sa.Column(
            "due_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Текущий дедлайн (TIMESTAMPTZ)",
        ),
        sa.Column(
            "extensions_count",
            sa.SmallInteger(),
            server_default=sa.text("0"),
            nullable=False,
            comment="Количество переносов дедлайна, CHECK 0..2",
        ),
        sa.Column(
            "submission_type",
            sa.VARCHAR(length=13),
            nullable=True,
            comment="files | self_reported (VARCHAR+CHECK); NULL до сдачи",
        ),
        sa.Column(
            "submitted_at", sa.DateTime(timezone=True), nullable=True, comment="Момент сдачи"
        ),
        sa.Column(
            "score",
            sa.SmallInteger(),
            nullable=True,
            comment="Балл (целое), CHECK >= 0; верхнюю границу проверяет сервис",
        ),
        sa.Column("graded_at", sa.DateTime(timezone=True), nullable=True, comment="Момент оценки"),
        sa.Column(
            "graded_by",
            sa.BIGINT(),
            nullable=True,
            comment="Кто оценил; при удалении аккаунта — NULL",
        ),
        sa.Column(
            "graded_after_expiry",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            nullable=False,
            comment="Оценено вручную уже после expired",
        ),
        sa.Column("teacher_comment", sa.Text(), nullable=True, comment="Комментарий преподавателя"),
        sa.Column(
            "student_comment", sa.Text(), nullable=True, comment="Комментарий ученика при сдаче"
        ),
        sa.Column(
            "expired_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Момент перехода в expired",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Время создания записи (TIMESTAMPTZ, UTC; docs/04 §0)",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Время последнего изменения; обновляется в приложении (docs/04 §0)",
        ),
        sa.CheckConstraint(
            "status IN ('assigned', 'submitted', 'needs_revision', 'graded', 'expired')",
            name=op.f("ck_homework_assignments_status"),
        ),
        sa.CheckConstraint(
            "submission_type IN ('files', 'self_reported')",
            name=op.f("ck_homework_assignments_submission_type"),
        ),
        sa.CheckConstraint(
            "extensions_count BETWEEN 0 AND 2",
            name=op.f("ck_homework_assignments_extensions_count_range"),
        ),
        sa.CheckConstraint("score >= 0", name=op.f("ck_homework_assignments_score_nonneg")),
        sa.ForeignKeyConstraint(
            ["graded_by"],
            ["users.id"],
            name=op.f("fk_homework_assignments_graded_by"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["homework_id"],
            ["homeworks.id"],
            name=op.f("fk_homework_assignments_homework_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["users.id"],
            name=op.f("fk_homework_assignments_student_id"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_homework_assignments")),
        sa.UniqueConstraint(
            "homework_id", "student_id", name=op.f("uq_homework_assignments_homework_id_student_id")
        ),
    )
    op.create_index(
        "ix_homework_assignments_status_due_at",
        "homework_assignments",
        ["status", "due_at"],
        unique=False,
    )
    op.create_index(
        "ix_homework_assignments_student_id_status",
        "homework_assignments",
        ["student_id", "status"],
        unique=False,
    )
    op.create_table(
        "homework_materials",
        sa.Column(
            "id",
            sa.BIGINT(),
            sa.Identity(always=True),
            nullable=False,
            comment="PK, BIGINT IDENTITY",
        ),
        sa.Column(
            "homework_id", sa.BIGINT(), nullable=False, comment="FK → homeworks, ON DELETE CASCADE"
        ),
        sa.Column(
            "s3_key",
            sa.VARCHAR(length=500),
            nullable=False,
            comment="Ключ объекта в S3 (UUID, не имя файла)",
        ),
        sa.Column(
            "original_name",
            sa.VARCHAR(length=255),
            nullable=False,
            comment="Исходное имя файла (только для показа)",
        ),
        sa.Column(
            "content_type",
            sa.VARCHAR(length=100),
            nullable=False,
            comment="MIME-тип, определённый по содержимому",
        ),
        sa.Column("size_bytes", sa.Integer(), nullable=False, comment="Размер файла, байты"),
        sa.ForeignKeyConstraint(
            ["homework_id"],
            ["homeworks.id"],
            name=op.f("fk_homework_materials_homework_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_homework_materials")),
    )
    op.create_table(
        "homework_extensions",
        sa.Column(
            "id",
            sa.BIGINT(),
            sa.Identity(always=True),
            nullable=False,
            comment="PK, BIGINT IDENTITY",
        ),
        sa.Column(
            "assignment_id",
            sa.BIGINT(),
            nullable=False,
            comment="FK → homework_assignments, ON DELETE CASCADE",
        ),
        sa.Column(
            "old_due_at", sa.DateTime(timezone=True), nullable=False, comment="Дедлайн до переноса"
        ),
        sa.Column(
            "new_due_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Дедлайн после переноса",
        ),
        sa.Column(
            "created_by",
            sa.BIGINT(),
            nullable=False,
            comment="Кто перенёс (персонал); FK → users, RESTRICT",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Время записи (TIMESTAMPTZ, UTC)",
        ),
        sa.ForeignKeyConstraint(
            ["assignment_id"],
            ["homework_assignments.id"],
            name=op.f("fk_homework_extensions_assignment_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_homework_extensions_created_by"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_homework_extensions")),
    )
    op.create_table(
        "homework_files",
        sa.Column(
            "id",
            sa.BIGINT(),
            sa.Identity(always=True),
            nullable=False,
            comment="PK, BIGINT IDENTITY",
        ),
        sa.Column(
            "assignment_id",
            sa.BIGINT(),
            nullable=False,
            comment="FK → homework_assignments, ON DELETE CASCADE",
        ),
        sa.Column(
            "uploaded_by", sa.BIGINT(), nullable=False, comment="Кто загрузил; FK → users, RESTRICT"
        ),
        sa.Column(
            "role",
            sa.VARCHAR(length=16),
            nullable=False,
            comment="student_solution | teacher_review (VARCHAR+CHECK)",
        ),
        sa.Column(
            "s3_key",
            sa.VARCHAR(length=500),
            nullable=False,
            comment="Ключ объекта в S3 (UUID, не имя файла)",
        ),
        sa.Column(
            "original_name",
            sa.VARCHAR(length=255),
            nullable=False,
            comment="Исходное имя файла (только для показа)",
        ),
        sa.Column(
            "content_type",
            sa.VARCHAR(length=100),
            nullable=False,
            comment="MIME-тип, определённый по содержимому",
        ),
        sa.Column("size_bytes", sa.Integer(), nullable=False, comment="Размер файла, байты"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Время загрузки (TIMESTAMPTZ, UTC)",
        ),
        sa.CheckConstraint(
            "role IN ('student_solution', 'teacher_review')", name=op.f("ck_homework_files_role")
        ),
        sa.ForeignKeyConstraint(
            ["assignment_id"],
            ["homework_assignments.id"],
            name=op.f("fk_homework_files_assignment_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by"],
            ["users.id"],
            name=op.f("fk_homework_files_uploaded_by"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_homework_files")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Откат миграции (удаляет всё, что создано в upgrade)."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("homework_files")
    op.drop_table("homework_extensions")
    op.drop_table("homework_materials")
    op.drop_index("ix_homework_assignments_student_id_status", table_name="homework_assignments")
    op.drop_index("ix_homework_assignments_status_due_at", table_name="homework_assignments")
    op.drop_table("homework_assignments")
    op.drop_table("homeworks")
    # ### end Alembic commands ###
