"""notifications t5 01

Revision ID: d5e6f7a8b9c0
Revises: c4d2e5f7a8b9
Create Date: 2026-10-07 16:17:31.289804+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "d5e6f7a8b9c0"
down_revision: str | None = "c4d2e5f7a8b9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Прямое применение миграции."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notifications",
        sa.Column(
            "id",
            sa.BIGINT(),
            sa.Identity(always=True),
            nullable=False,
            comment="PK, BIGINT IDENTITY",
        ),
        sa.Column(
            "user_id",
            sa.BIGINT(),
            nullable=False,
            comment="Получатель; при удалении пользователя его очередь удаляется",
        ),
        sa.Column(
            "type",
            sa.VARCHAR(length=50),
            nullable=False,
            comment="Тип уведомления (lesson_reminder, homework_graded, …), список в docs/05 §6",
        ),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
            comment="Данные для шаблона: id сущностей и значения",
        ),
        sa.Column(
            "dedup_key", sa.VARCHAR(length=200), nullable=False, comment="Ключ дедупликации, UNIQUE"
        ),
        sa.Column(
            "is_urgent",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            nullable=False,
            comment="Срочное: игнорирует тихие часы",
        ),
        sa.Column(
            "scheduled_for",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Не раньше этого момента (TIMESTAMPTZ)",
        ),
        sa.Column(
            "status",
            sa.VARCHAR(length=7),
            server_default=sa.text("'pending'"),
            nullable=False,
            comment="pending | sent | failed | skipped (VARCHAR+CHECK)",
        ),
        sa.Column(
            "attempts",
            sa.SmallInteger(),
            server_default=sa.text("0"),
            nullable=False,
            comment="Число попыток отправки",
        ),
        sa.Column(
            "sent_at", sa.DateTime(timezone=True), nullable=True, comment="Момент успешной отправки"
        ),
        sa.Column(
            "last_error", sa.Text(), nullable=True, comment="Текст последней ошибки отправки"
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Время создания записи (TIMESTAMPTZ, UTC; docs/04 §0)",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Время последнего изменения; обновляется в приложении (docs/04 §0)",
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'sent', 'failed', 'skipped')",
            name=op.f("ck_notifications_status"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_notifications_user_id"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
        sa.UniqueConstraint("dedup_key", name=op.f("uq_notifications_dedup_key")),
    )
    op.create_index(
        "ix_notifications_status_scheduled_for",
        "notifications",
        ["status", "scheduled_for"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Откат миграции (удаляет всё, что создано в upgrade)."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_notifications_status_scheduled_for", table_name="notifications")
    op.drop_table("notifications")
    # ### end Alembic commands ###
