"""initial schema t1 02 core tables

Revision ID: fddb2f6cef06
Revises:
Create Date: 2026-10-06 15:31:17.398942+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "fddb2f6cef06"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Расширение btree_gist — требование docs/04 §0: нужно для GiST-индексов
    # исключающих ограничений на этапах расписания. Создаётся один раз;
    # IF NOT EXISTS делает повторный прогон безопасным.
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "subjects",
        sa.Column(
            "id",
            sa.BIGINT(),
            sa.Identity(always=True),
            nullable=False,
            comment="PK, BIGINT IDENTITY",
        ),
        sa.Column(
            "code", sa.VARCHAR(length=32), nullable=False, comment="Машинный код: informatics, math"
        ),
        sa.Column("name", sa.VARCHAR(length=100), nullable=False, comment="Отображаемое имя"),
        sa.Column(
            "is_active",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            nullable=False,
            comment="Предмет доступен для выбора",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Время создания записи (TIMESTAMPTZ, UTC; docs/04 §0)",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Время последнего изменения; обновляется в приложении (docs/04 §0)",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subjects")),
        sa.UniqueConstraint("code", name=op.f("uq_subjects_code")),
    )
    op.create_table(
        "users",
        sa.Column(
            "id",
            sa.BIGINT(),
            sa.Identity(always=True),
            nullable=False,
            comment="PK, BIGINT IDENTITY",
        ),
        sa.Column(
            "role",
            sa.VARCHAR(length=7),
            nullable=False,
            comment="Роль: owner | manager | student (VARCHAR+CHECK)",
        ),
        sa.Column(
            "telegram_id",
            sa.BIGINT(),
            nullable=True,
            comment="Telegram ID (BIGINT: значения > 2^31, docs/04 §0); NULL — профиль ждёт приглашение",  # noqa: E501
        ),
        sa.Column(
            "telegram_username",
            sa.VARCHAR(length=64),
            nullable=True,
            comment="Для удобства отображения, не для идентификации",
        ),
        sa.Column(
            "display_name",
            sa.VARCHAR(length=150),
            nullable=False,
            comment="Как обращаться к человеку",
        ),
        sa.Column(
            "timezone",
            sa.VARCHAR(length=64),
            server_default=sa.text("'Europe/Moscow'"),
            nullable=False,
            comment="IANA-часовой пояс пользователя",
        ),
        sa.Column(
            "is_active",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            nullable=False,
            comment="false = архив (мягкое удаление, docs/04 §0)",
        ),
        sa.Column(
            "archived_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Момент архивации (TIMESTAMPTZ)",
        ),
        sa.Column(
            "bot_blocked",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            nullable=False,
            comment="Пользователь заблокировал бота",
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Последняя активность (TIMESTAMPTZ)",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Время создания записи (TIMESTAMPTZ, UTC; docs/04 §0)",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Время последнего изменения; обновляется в приложении (docs/04 §0)",
        ),
        sa.CheckConstraint("role IN ('owner', 'manager', 'student')", name=op.f("ck_users_role")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("telegram_id", name=op.f("uq_users_telegram_id")),
    )
    op.create_table(
        "audit_log",
        sa.Column(
            "id",
            sa.BIGINT(),
            sa.Identity(always=True),
            nullable=False,
            comment="PK, BIGINT IDENTITY",
        ),
        sa.Column(
            "actor_user_id",
            sa.BIGINT(),
            nullable=True,
            comment="Кто выполнил действие; журнал сохраняется при удалении пользователя (docs/09 §8)",  # noqa: E501
        ),
        sa.Column(
            "action",
            sa.VARCHAR(length=80),
            nullable=False,
            comment="lesson.rescheduled, student.price_changed, invite.created, …",
        ),
        sa.Column("entity_type", sa.VARCHAR(length=50), nullable=False, comment="Тип сущности"),
        sa.Column(
            "entity_id",
            sa.BIGINT(),
            nullable=True,
            comment="ID сущности (NULL — если сущность удалена)",
        ),
        sa.Column(
            "data",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
            comment="Было/стало",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Момент события (TIMESTAMPTZ); единственная временная колонка журнала",
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_audit_log_actor_user_id"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    op.create_table(
        "auth_tokens",
        sa.Column(
            "id",
            sa.BIGINT(),
            sa.Identity(always=True),
            nullable=False,
            comment="PK, BIGINT IDENTITY",
        ),
        sa.Column(
            "purpose",
            sa.VARCHAR(length=9),
            nullable=False,
            comment="Назначение: invite | web_login (VARCHAR+CHECK)",
        ),
        sa.Column(
            "user_id",
            sa.BIGINT(),
            nullable=False,
            comment="Для кого токен; FK → users, ON DELETE CASCADE (токен без владельца не нужен)",
        ),
        sa.Column(
            "token_hash",
            sa.CHAR(length=64),
            nullable=False,
            comment="SHA-256 от токена (64 hex-символа); сам токен не хранится (docs/09 §2.1)",
        ),
        sa.Column(
            "created_by",
            sa.BIGINT(),
            nullable=True,
            comment="Кто создал; NULL для web_login; при удалении создателя — NULL",
        ),
        sa.Column(
            "expires_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Срок действия: invite +7 дней, web_login +10 минут (TIMESTAMPTZ)",
        ),
        sa.Column(
            "used_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Момент погашения (одноразовость)",
        ),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True, comment="Момент отзыва"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Время создания записи (TIMESTAMPTZ, UTC; docs/04 §0)",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Время последнего изменения; обновляется в приложении (docs/04 §0)",
        ),
        sa.CheckConstraint(
            "purpose IN ('invite', 'web_login')", name=op.f("ck_auth_tokens_purpose")
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_auth_tokens_created_by"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_auth_tokens_user_id"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_auth_tokens")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_auth_tokens_token_hash")),
    )
    op.create_index(
        "ix_auth_tokens_user_id_purpose", "auth_tokens", ["user_id", "purpose"], unique=False
    )
    op.create_table(
        "exam_types",
        sa.Column(
            "id",
            sa.BIGINT(),
            sa.Identity(always=True),
            nullable=False,
            comment="PK, BIGINT IDENTITY",
        ),
        sa.Column(
            "code",
            sa.VARCHAR(length=32),
            nullable=False,
            comment="Машинный код: oge_informatics, oge_math, ege_informatics, ege_math_profile",
        ),
        sa.Column(
            "subject_id",
            sa.BIGINT(),
            nullable=False,
            comment="FK → subjects (справочник не удаляют, пока на него есть ссылки)",
        ),
        sa.Column(
            "kind",
            sa.VARCHAR(length=3),
            nullable=False,
            comment="Вид экзамена: oge | ege (VARCHAR+CHECK)",
        ),
        sa.Column(
            "result_kind",
            sa.VARCHAR(length=9),
            nullable=False,
            comment="Результат шкалы: grade_2_5 | test_100 (VARCHAR+CHECK)",
        ),
        sa.Column(
            "max_primary",
            sa.SmallInteger(),
            nullable=False,
            comment="Максимальный первичный балл текущего года",
        ),
        sa.Column("name", sa.VARCHAR(length=100), nullable=False, comment="Отображаемое имя"),
        sa.Column(
            "config",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
            comment="Особые правила, напр. {'min_geometry': 2} для ОГЭ математики",
        ),
        sa.Column(
            "is_active",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            nullable=False,
            comment="Тип доступен для выбора",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Время создания записи (TIMESTAMPTZ, UTC; docs/04 §0)",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Время последнего изменения; обновляется в приложении (docs/04 §0)",
        ),
        sa.CheckConstraint(
            "result_kind IN ('grade_2_5', 'test_100')", name=op.f("ck_exam_types_result_kind")
        ),
        sa.CheckConstraint("kind IN ('oge', 'ege')", name=op.f("ck_exam_types_kind")),
        sa.ForeignKeyConstraint(
            ["subject_id"],
            ["subjects.id"],
            name=op.f("fk_exam_types_subject_id"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exam_types")),
        sa.UniqueConstraint("code", name=op.f("uq_exam_types_code")),
    )
    op.create_table(
        "guardians",
        sa.Column(
            "id",
            sa.BIGINT(),
            sa.Identity(always=True),
            nullable=False,
            comment="PK, BIGINT IDENTITY",
        ),
        sa.Column(
            "student_id",
            sa.BIGINT(),
            nullable=False,
            comment="FK → users (ученик), ON DELETE CASCADE (docs/04 §2.4)",
        ),
        sa.Column("full_name", sa.VARCHAR(length=150), nullable=False, comment="ФИО представителя"),
        sa.Column(
            "relation",
            sa.VARCHAR(length=50),
            nullable=True,
            comment="Кем приходится: мама, папа, …",
        ),
        sa.Column(
            "phone",
            sa.VARCHAR(length=32),
            nullable=True,
            comment="Телефон (минимизация PII: необязательно, docs/09 §7)",
        ),
        sa.Column(
            "telegram_id",
            sa.BIGINT(),
            nullable=True,
            comment="Telegram ID представителя (BIGINT, docs/04 §0)",
        ),
        sa.Column(
            "user_id",
            sa.BIGINT(),
            nullable=True,
            comment="Для будущей роли parent; колонка NULL-допустима, при удалении аккаунта — NULL",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Время создания записи (TIMESTAMPTZ, UTC; docs/04 §0)",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Время последнего изменения; обновляется в приложении (docs/04 §0)",
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["users.id"],
            name=op.f("fk_guardians_student_id_fk"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_guardians_linked_user_id_fk"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_guardians")),
    )
    op.create_table(
        "student_profiles",
        sa.Column(
            "user_id",
            sa.BIGINT(),
            nullable=False,
            comment="PK и FK → users, ON DELETE CASCADE (docs/04 §2.2)",
        ),
        sa.Column(
            "teacher_id",
            sa.BIGINT(),
            nullable=False,
            comment="Ведущий преподаватель (owner/manager); RESTRICT — профиль всегда кому-то принадлежит",  # noqa: E501
        ),
        sa.Column("school_class", sa.SmallInteger(), nullable=True, comment="Класс (9, 11, …)"),
        sa.Column(
            "lesson_price",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
            comment="Текущая цена занятия в рублях, CHECK >= 0; видит только owner (docs/09 §3)",
        ),
        sa.Column(
            "video_url",
            sa.VARCHAR(length=500),
            nullable=True,
            comment="Постоянная ссылка Яндекс Телемоста",
        ),
        sa.Column(
            "board_url",
            sa.VARCHAR(length=500),
            nullable=True,
            comment="Постоянная ссылка на онлайн-доску",
        ),
        sa.Column(
            "teacher_notes",
            sa.Text(),
            nullable=True,
            comment="Приватные заметки преподавателя (ученик не видит)",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Время создания записи (TIMESTAMPTZ, UTC; docs/04 §0)",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Время последнего изменения; обновляется в приложении (docs/04 §0)",
        ),
        sa.CheckConstraint(
            "lesson_price >= 0", name=op.f("ck_student_profiles_lesson_price_nonneg")
        ),
        sa.ForeignKeyConstraint(
            ["teacher_id"],
            ["users.id"],
            name=op.f("fk_student_profiles_teacher_id"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_student_profiles_student_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_student_profiles")),
    )
    op.create_table(
        "student_subjects",
        sa.Column(
            "student_id",
            sa.BIGINT(),
            nullable=False,
            comment="FK → users (ученик), ON DELETE CASCADE",
        ),
        sa.Column(
            "subject_id",
            sa.BIGINT(),
            nullable=False,
            comment="FK → subjects, ON DELETE CASCADE (связь live-объектов, docs/04 §0)",
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["users.id"],
            name=op.f("fk_student_subjects_student_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["subject_id"],
            ["subjects.id"],
            name=op.f("fk_student_subjects_subject_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("student_id", "subject_id", name=op.f("pk_student_subjects")),
    )
    op.create_table(
        "grade_scales",
        sa.Column(
            "id",
            sa.BIGINT(),
            sa.Identity(always=True),
            nullable=False,
            comment="PK, BIGINT IDENTITY",
        ),
        sa.Column(
            "exam_type_id",
            sa.BIGINT(),
            nullable=False,
            comment="FK → exam_types, ON DELETE CASCADE (docs/04 §1.3)",
        ),
        sa.Column("valid_year", sa.SmallInteger(), nullable=False, comment="Год действия шкалы"),
        sa.Column("primary_score", sa.SmallInteger(), nullable=False, comment="Первичный балл"),
        sa.Column(
            "result_value",
            sa.SmallInteger(),
            nullable=False,
            comment="Оценка 2–5 (ОГЭ) или тестовый балл 0–100 (ЕГЭ)",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Время создания записи (TIMESTAMPTZ, UTC; docs/04 §0)",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Время последнего изменения; обновляется в приложении (docs/04 §0)",
        ),
        sa.CheckConstraint("primary_score >= 0", name=op.f("ck_grade_scales_primary_score_nonneg")),
        sa.ForeignKeyConstraint(
            ["exam_type_id"],
            ["exam_types.id"],
            name=op.f("fk_grade_scales_exam_type_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_grade_scales")),
        sa.UniqueConstraint(
            "exam_type_id",
            "valid_year",
            "primary_score",
            name=op.f("uq_grade_scales_exam_type_id_valid_year_primary_score"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Откат миграции (удаляет всё, что создано в upgrade)."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("grade_scales")
    op.drop_table("student_subjects")
    op.drop_table("student_profiles")
    op.drop_table("guardians")
    op.drop_table("exam_types")
    op.drop_index("ix_auth_tokens_user_id_purpose", table_name="auth_tokens")
    op.drop_table("auth_tokens")
    op.drop_table("audit_log")
    op.drop_table("users")
    op.drop_table("subjects")
    # Расширение btree_gist создавалось в upgrade; при откате удаляем его,
    # чтобы downgrade полностью снимал всё созданное миграцией.
    op.execute("DROP EXTENSION IF EXISTS btree_gist")
    # ### end Alembic commands ###
