/**
 * ВСЕ тексты интерфейса живут здесь (docs/12 §10.2, docs/06 B3).
 * Язык — русский, идентификаторы — английские.
 * Пока минимальный набор ключей для каркаса; расширяется по мере появления экранов.
 */
export const texts = {
  app: {
    title: "Ромчик",
    greeting: "Привет, Ромчик",
  },
  login: {
    title: "Ромчик | ИнфоМат",
    openViaBot: "Войди через Telegram-бота",
    openBot: "Открыть бота",
    signingIn: "Входим…",
    retry: "Повторить",
    linkHint: "Нажми «Войти», чтобы открыть приложение. Ссылка сработает только один раз.",
    linkButton: "Войти",
  },
  hello: {
    greeting: "Привет, {name}",
    roleLabel: "Роль",
  },
  roles: {
    student: "Ученик",
    manager: "Менеджер",
    owner: "Владелец",
  },
  common: {
    loading: "Загрузка…",
    back: "Назад",
    cancel: "Отмена",
    save: "Сохранить",
    close: "Закрыть",
    logout: "Выход",
    logoutFailed: "Не получилось выйти. Попробуй ещё раз",
    mainNavigation: "Основная навигация",
    brand: "Ромчик | ИнфоМат",
    brandFirst: "Ромчик",
    brandSecond: "ИнфоМат",
    profileAvatar: "Профиль",
    notFound: "Эта страница недоступна",
    toHome: "На главную",
    chooseSubject: "Выберите предмет",
  },
  nav: {
    student: {
      schedule: "Расписание",
      homework: "ДЗ",
      reports: "Отчёты",
    },
    admin: {
      today: "Сегодня",
      schedule: "Расписание",
      homework: "ДЗ",
      students: "Ученики",
      more: "Ещё",
      exams: "Пробники",
      catalog: "Каталог",
      finance: "Финансы",
      staff: "Сотрудники",
    },
  },
  /** Пустые состояния (docs/07 §6.16, §8.2) */
  empty: {
    studentSchedule: {
      title: "Расписание",
      text: "Пока уроков нет. Роман добавит расписание, и оно появится здесь",
    },
    studentHomework: {
      title: "ДЗ",
      text: "Все ДЗ сделаны. Новые появятся здесь",
    },
    studentReports: {
      title: "Отчёты",
      text: "Пока мало данных. Графики появятся после первых проверенных ДЗ",
    },
    adminStudents: {
      title: "Ученики",
      text: "Учеников пока нет. Создайте первый профиль",
    },
    adminReviewQueue: {
      title: "ДЗ",
      text: "Очередь пуста. Всё проверено",
    },
    soon: "Раздел скоро появится",
  },
  /** Профиль (docs/07 §9.1.7) */
  profile: {
    title: "Профиль",
    name: "Имя",
    timezone: "Часовой пояс",
    timezoneHint: "По нему показывается время уроков",
    nameRequired: "Введи имя",
    nameTooLong: "Не длиннее 150 символов",
    save: "Сохранить",
    webLogin: "Войти в браузере",
    webLoginHint: "Открой бота и отправь команду /web: бот пришлёт одноразовую ссылку для входа",
    openBot: "Открыть бота",
    logout: "Выйти",
    logoutFailed: "Не получилось выйти. Попробуй ещё раз",
  },
  /** Конвертация баллов пробников (docs/04 §6, docs/07 §9.2.9–9.2.10): тексты считает фронтенд только как подписи */
  exams: {
    gradeOf: (primary: number, value: number) =>
      `${String(primary)} баллов = оценка ${String(value)}`,
    testOf: (primary: number, value: number) =>
      `${String(primary)} баллов = тестовый ${String(value)}`,
    notApplicable: "Шкала не применима (нестандартный максимум)",
    geometryMissing: "Баллы по геометрии не указаны: расчёт по сумме",
    gradeLabel: (value: number) => `оценка ${String(value)}`,
    testLabel: (value: number) => `тестовый ${String(value)}`,
  },
  /** Расписание ученика (docs/07 §9.1.1–9.1.3) */
  student: {
    homework: {
      title: "ДЗ",
      tabActive: "Активные",
      tabSubmitted: "На проверке",
      tabGraded: "Проверено",
      tabExpired: "Сгорело",
      empty: {
        active: "Все ДЗ сделаны. Новые появятся здесь",
        submitted: "Пока ничего не ждёт проверки",
        graded: "Проверенных работ пока нет",
        expired: "Сгоревших ДЗ нет",
      },
      loadError: "Не получилось загрузить ДЗ",
      loadMore: "Показать ещё",
      back: "К списку ДЗ",
      dueAt: (value: string) => `Срок: ${value}`,
      extensionsLeft: (left: number) => `Можно перенести срок ещё раз: ${String(left)}`,
      materials: "Материалы",
      yourSolution: "Твоё решение",
      comment: "Комментарий (необязательно)",
      submit: "Сдать",
      submitHint: "Сначала добавь хотя бы один файл",
      selfReport: "Сделал",
      selfReportHint: "Для заданий без файлов, например устных",
      submitted: "Работа сдана и ждёт проверки",
      submittedOnTime: "Сдано в срок",
      submittedLate: "Сдано позже срока",
      submitDone: "Работа сдана",
      expired: "Срок сдачи закончился. Напиши преподавателю, если нужна помощь",
      revision: "Нужно доработать",
      teacherComment: "Комментарий преподавателя",
      reviewFiles: "Файлы проверки",
      result: (score: number, max: number, percent: number | null) =>
        percent === null
          ? `${String(score)} из ${String(max)}`
          : `${String(score)} из ${String(max)} · ${String(percent)}%`,
      openFile: "Открыть",
      removeFile: (name: string) => `Удалить файл ${name}`,
      uploader: {
        add: "Добавить фото или файл",
        hint: "jpg, png, heic или pdf, до 10 МБ, не больше 10 файлов",
        uploading: (name: string, percent: number) => `${name}: ${String(percent)}%`,
        limitReached: "Уже загружено 10 файлов — больше нельзя",
        tooLarge: "Файл больше 10 МБ",
        wrongType: "Подходят только jpg, png, heic и pdf",
        failed: "Не получилось загрузить файл. Попробуй ещё раз",
      },
    },
    reports: {
      periods: { weeks4: "4 недели", months3: "3 месяца", all: "Всё" },
      periodLabel: "Период",
      loadError: "Не получилось загрузить отчёт",
      empty: "Пока мало данных. Графики появятся после первых проверенных ДЗ",
      homework: {
        title: "Средний процент ДЗ",
        axisWeek: "Неделя",
        axisPercent: "Процент",
        series: "Средний процент",
        last: (percent: number) => `Последний результат: ${String(percent)}%`,
        weekPoint: (week: string, percent: number, count: number) =>
          `неделя с ${week}: ${String(percent)}% (проверено работ: ${String(count)})`,
        none: "Проверенных ДЗ за период нет",
      },
      mock: {
        title: "Пробные экзамены",
        axisDate: "Дата",
        axisPercent: "Процент от максимума",
        series: "Процент от максимума",
        none: "Пробных экзаменов за период нет",
        point: (date: string, name: string, result: string) => `${date}, ${name}: ${result}`,
      },
      onTime: {
        title: "Сдано в срок",
        value: (percent: number) => `${String(percent)}%`,
        detail: (onTime: number, total: number) => `${String(onTime)} из ${String(total)}`,
        none: "Сданных ДЗ за период нет",
      },
    },
    schedule: {
      today: "Сегодня",
      tomorrow: "Завтра",
      nextLesson: "Ближайший урок",
      list: "Список",
      week: "Неделя",
      prevWeek: "Предыдущая неделя",
      nextWeek: "Следующая неделя",
      thisWeek: "Эта неделя",
      loadError: "Не получилось загрузить расписание",
      noLessonsWeek: "На этой неделе уроков нет",
      until: (minutes: number): string => {
        if (minutes <= 0) return "идёт сейчас";
        if (minutes < 60) return `через ${String(minutes)} мин`;
        if (minutes < 24 * 60) {
          const hours = Math.floor(minutes / 60);
          const rest = minutes % 60;
          return rest === 0
            ? `через ${String(hours)} ч`
            : `через ${String(hours)} ч ${String(rest)} мин`;
        }
        return `через ${String(Math.floor(minutes / (24 * 60)))} дн.`;
      },
      card: {
        back: "К расписанию",
        notFound: "Урок не найден",
        group: (count: number) => `Групповой урок · ${String(count)} уч.`,
        video: "Телемост",
        board: "Доска",
        noLinks: "Ссылку добавит Роман",
        topic: "Тема",
        homework: "Домашнее задание",
        homeworkDue: (value: string) => `Сдать до ${value}`,
      },
    },
  },
  /** Админка: ученики, сотрудники, приглашения (docs/07 §9.2.2–9.2.4, §9.2.13) */
  admin: {
    exams: {
      title: "Пробники",
      newResult: "Ввести результат",
      filterStudent: "Ученик",
      filterExam: "Экзамен",
      all: "Все",
      loadError: "Не получилось загрузить результаты",
      empty: "Результатов пробников пока нет",
      loadMore: "Показать ещё",
      delete: "Удалить",
      deleteTitle: "Удалить результат пробника?",
      deleteConfirm: "Удалить результат",
      deleted: "Результат удалён",
      fromHomework: "Из ДЗ",
      saved: "Результат сохранён",
      row: (primary: number, max: number) => `${String(primary)} из ${String(max)}`,
      form: {
        title: "Результат пробника",
        student: "Ученик",
        studentPlaceholder: "Выберите ученика",
        exam: "Экзамен",
        examPlaceholder: "Выберите экзамен",
        date: "Дата экзамена",
        primary: "Первичный балл",
        max: "Максимум варианта",
        maxHint: "Официальный максимум подставлен сам; другое значение отключает шкалу",
        geometry: "Баллы по геометрии",
        geometryHint: "ОГЭ математика: меньше 2 баллов — оценка 2",
        comment: "Комментарий",
        submit: "Сохранить результат",
        conversion: "Конвертация",
        errors: {
          studentRequired: "Выберите ученика",
          examRequired: "Выберите экзамен",
          dateRequired: "Укажите дату",
          primaryRange: "Первичный балл — целое число от 0",
          maxRange: "Максимум — целое число от 1",
          scoreAboveMax: "Первичный балл больше максимума",
          geometryRange: "Баллы по геометрии — целое число от 0",
          geometryAbovePrimary: "Баллов по геометрии больше, чем первичных",
          commentTooLong: "Не длиннее 2000 символов",
        },
      },
    },
    homework: {
      title: "ДЗ",
      newHomework: "Новое ДЗ",
      tabQueue: "На проверке",
      tabHomework: "Задания",
      queueEmpty: "Очередь пуста. Всё проверено",
      listEmpty: "Заданий пока нет. Создай первое",
      loadError: "Не получилось загрузить ДЗ",
      submittedOf: (submitted: number, assigned: number) =>
        `сдали ${String(submitted)} из ${String(assigned)}`,
      scoreOf: (max: number) => `из ${String(max)}`,
      submittedAt: (value: string) => `Сдано ${value}`,
      dueAt: (value: string) => `Срок ${value}`,
      loadMore: "Показать ещё",
      kind: { regular: "Обычное", mock_exam: "Пробник" },
      form: {
        title: "Новое ДЗ",
        kind: "Тип",
        name: "Название",
        description: "Описание",
        subject: "Предмет",
        maxScore: "Число заданий",
        maxScoreHint: "1 задание = 1 балл",
        dueMode: "Срок",
        dueNextLesson: "Следующее занятие",
        dueFixed: "Дата",
        date: "Дата срока",
        time: "Время срока",
        fallbackHint: "Если у ученика нет занятия, срок будет этим",
        material: "Материал к заданию",
        materialHint: "jpg, png, heic или pdf, до 10 МБ",
        students: "Ученики",
        selectAll: "Выбрать всех",
        submit: "Выдать ДЗ",
        created: "ДЗ выдано",
        materialFailed: "ДЗ выдано, но материал не загрузился. Добавь его позже",
        errors: {
          nameRequired: "Введи название",
          nameTooLong: "Не длиннее 255 символов",
          descriptionTooLong: "Не длиннее 5000 символов",
          maxScoreRange: "Число заданий — целое от 1 до 100",
          dateRequired: "Выбери дату срока",
          timeRequired: "Выбери время срока",
          studentsRequired: "Выбери хотя бы одного ученика",
          subjectRequired: "Выберите предмет",
        },
      },
      detail: {
        back: "К списку ДЗ",
        materials: "Материалы",
        assignments: "Выдачи",
        notFound: "ДЗ не найдено",
        open: "Проверить",
      },
      review: {
        title: "Проверка ДЗ",
        back: "К очереди",
        studentFiles: "Работа ученика",
        noFiles: "Ученик сдал без файлов («Сделал»)",
        studentComment: "Комментарий ученика",
        score: "Балл",
        comment: "Комментарий",
        save: "Сохранить оценку",
        saved: "Оценка сохранена",
        returnButton: "Вернуть на доработку",
        returnTitle: "Вернуть на доработку",
        returnComment: "Что исправить",
        returnDue: "Новый срок (необязательно)",
        returnDueHint: "Без даты — до следующего занятия",
        returnSubmit: "Вернуть",
        returned: "Работа возвращена",
        extend: "Перенести на следующее занятие",
        extendLeft: (left: number, max: number) => `Осталось ${String(left)} из ${String(max)}`,
        extendNone: "Переносы закончились: больше двух раз нельзя",
        extendManual: "Следующего занятия нет. Выбери срок вручную",
        extendManualSubmit: "Перенести на дату",
        extended: "Срок перенесён",
        reviewFiles: "Файлы проверки",
        addReviewFile: "Добавить файл проверки",
        uploaded: "Файл загружен",
        notReviewable: "Эту работу уже нельзя изменить",
        graded: (score: number, max: number, percent: number | null) =>
          `Оценка: ${String(score)} из ${String(max)}${percent === null ? "" : ` (${String(percent)}%)`}`,
        mockConversion: "Конвертация пробника",
        geometry: "Баллы по геометрии",
        geometryHint: "ОГЭ математика: меньше 2 баллов — оценка 2",
        extensionsLog: "Переносы срока",
        extensionRow: (from: string, to: string) => `${from} → ${to}`,
        onTime: "Сдано в срок",
        late: "Сдано позже срока",
        openFile: "Открыть файл",
        zoomIn: "Увеличить",
        zoomOut: "Уменьшить",
        prev: "Предыдущий файл",
        next: "Следующий файл",
        fileOf: (index: number, total: number) => `${String(index)} из ${String(total)}`,
        errors: {
          scoreRange: (max: number) => `Балл — целое от 0 до ${String(max)}`,
          commentRequired: "Напиши, что исправить",
          commentTooLong: "Не длиннее 5000 символов",
          geometryRange: "Баллы по геометрии — целое число от 0",
          dateRequired: "Выбери дату",
          timeRequired: "Выбери время",
        },
      },
    },
    students: {
      newStudent: "Новый ученик",
      search: "Поиск по имени",
      filterActive: "Активные",
      filterArchived: "Архив",
      classLabel: (value: number) => `${String(value)} класс`,
      invitePending: "Приглашение не принято",
      listLoadError: "Не получилось загрузить учеников",
      noResults: "Никого не нашли. Измени поиск",
      noArchived: "В архиве никого нет",
      loadMore: "Показать ещё",
      archivedBadge: "В архиве",
      tabs: { overview: "Обзор", progress: "Пробники и прогресс", finance: "Финансы" },
      overview: {
        profile: "Профиль",
        timezone: "Часовой пояс",
        subjects: "Предметы",
        video: "Телемост",
        board: "Доска",
        notes: "Заметки преподавателя",
        notesPrivate: "Видны только персоналу",
        none: "Не указано",
        telegram: "Telegram",
        telegramLinked: "Подключён",
        telegramNotLinked: "Не подключён",
      },
      finance: { lessonPrice: "Цена занятия", perLesson: (value: string) => `${value} ₽ за урок` },
      actions: {
        edit: "Редактировать",
        invite: "Приглашение",
        archive: "Архивировать",
        restore: "Вернуть из архива",
        unlink: "Отвязать Telegram",
        back: "К списку",
      },
      archiveTitle: (name: string) => `Архивировать ${name}?`,
      archiveText: "Данные и статистика сохранятся, вход будет закрыт",
      archiveConfirm: "Архивировать",
      unlinkTitle: (name: string) => `Отвязать Telegram у ${name}?`,
      unlinkText: "Ученик не сможет войти, пока не получит новое приглашение",
      unlinkConfirm: "Отвязать",
      notFound: "Ученик не найден",
      form: {
        createTitle: "Новый ученик",
        editTitle: "Редактирование",
        name: "Имя",
        schoolClass: "Класс",
        subjects: "Предметы",
        timezone: "Часовой пояс",
        video: "Ссылка на Телемост",
        board: "Ссылка на доску",
        price: "Цена занятия, ₽",
        notes: "Заметки преподавателя",
        submitCreate: "Создать ученика",
        submitEdit: "Сохранить",
        errors: {
          nameRequired: "Введи имя",
          nameTooLong: "Не длиннее 150 символов",
          classRange: "Класс — число от 1 до 11",
          urlHttps: "Ссылка должна начинаться с https://",
          urlTooLong: "Не длиннее 500 символов",
          priceRange: "Цена — целое число от 0 до 1 000 000",
          notesTooLong: "Не длиннее 5000 символов",
          timezoneRequired: "Выбери часовой пояс",
        },
      },
    },
    schedule: {
      title: "Расписание",
      newLesson: "Новый урок",
      newTemplate: "Новый шаблон",
      today: "Сегодня",
      prevWeek: "Предыдущая неделя",
      nextWeek: "Следующая неделя",
      prevDay: "Предыдущий день",
      nextDay: "Следующий день",
      weekOf: (from: string, to: string) => `${from} — ${to}`,
      filterStudent: "Ученик",
      filterStatus: "Статус",
      allStudents: "Все ученики",
      allStatuses: "Все статусы",
      loadError: "Не получилось загрузить расписание",
      noLessonsDay: "В этот день уроков нет",
      noLessonsWeek: "На этой неделе уроков нет",
      emptyHint: "Создайте урок или шаблон «каждую неделю»",
      participantsCount: (count: number) => `${String(count)} уч.`,
      groupLesson: "Групповой урок",
      form: {
        createTitle: "Новый урок",
        subject: "Предмет",
        participants: "Участники",
        searchStudents: "Найти ученика",
        noStudents: "Нет активных учеников. Сначала создайте ученика",
        date: "Дата",
        time: "Время начала",
        duration: "Длительность, минут",
        video: "Ссылка на Телемост (необязательно)",
        board: "Ссылка на доску (необязательно)",
        topic: "Тема (необязательно)",
        submitCreate: "Создать урок",
        timezoneHint: (zone: string) => `Время указывается в вашем часовом поясе: ${zone}`,
        errors: {
          subjectRequired: "Выберите предмет",
          participantsRequired: "Выберите хотя бы одного ученика",
          participantsTooMany: "Не больше 20 участников",
          dateRequired: "Укажите дату",
          timeRequired: "Укажите время",
          durationRange: "Длительность — от 1 до 720 минут",
          urlHttps: "Ссылка должна начинаться с https://",
          topicTooLong: "Не длиннее 255 символов",
        },
      },
      template: {
        createTitle: "Новый шаблон «каждую неделю»",
        weekday: "День недели",
        weekdays: [
          "Понедельник",
          "Вторник",
          "Среда",
          "Четверг",
          "Пятница",
          "Суббота",
          "Воскресенье",
        ],
        startsOn: "Начинать с",
        endsOn: "Закончить (необязательно)",
        preview: "Ближайшие даты",
        previewEmpty: "В выбранном периоде дат нет",
        submit: "Создать шаблон",
        created: "Шаблон создан, уроки добавлены в расписание",
        periodError: "Дата окончания раньше даты начала",
      },
      detail: {
        participants: "Участники",
        links: "Ссылки",
        video: "Телемост",
        board: "Доска",
        none: "Не указано",
        topic: "Тема",
        note: "Заметка преподавателя",
        cancelReason: "Причина отмены",
        detached: "Изменён вручную",
        actions: { complete: "Отметить проведение", reschedule: "Перенести", cancel: "Отменить" },
        back: "Назад",
      },
      complete: {
        title: "Отметка проведения",
        attended: "Был",
        noShow: "Не пришёл",
        cancelled: "Отменено",
        billable: "Засчитать занятие",
        submit: "Завершить урок",
        done: "Урок отмечен как проведённый",
      },
      reschedule: { title: "Перенос урока", submit: "Перенести урок", done: "Урок перенесён" },
      cancel: {
        title: (when: string) => `Отменить урок ${when}?`,
        text: "Ученики увидят урок как отменённый. Вернуть его нельзя.",
        reason: "Причина (необязательно)",
        billable: "Засчитать отмену",
        submit: "Отменить урок",
        done: "Урок отменён",
      },
      generate: { done: "Расписание дополнено" },
    },
    timezones: {
      "Europe/Moscow": "Москва (UTC+3)",
      "Europe/Samara": "Самара (UTC+4)",
      "Asia/Yekaterinburg": "Екатеринбург (UTC+5)",
      "Asia/Omsk": "Омск (UTC+6)",
      "Asia/Novosibirsk": "Новосибирск (UTC+7)",
      "Asia/Krasnoyarsk": "Красноярск (UTC+7)",
      "Asia/Irkutsk": "Иркутск (UTC+8)",
      "Asia/Yakutsk": "Якутск (UTC+9)",
      "Asia/Vladivostok": "Владивосток (UTC+10)",
      "Europe/Kaliningrad": "Калининград (UTC+2)",
    },
    invitation: {
      title: "Приглашение",
      preparing: "Готовим ссылку…",
      hint: "Откроется один раз. Действует 7 дней",
      copy: "Скопировать",
      copied: "Ссылка скопирована",
      copyFailed: "Не получилось скопировать. Выдели ссылку и скопируй вручную",
      share: "Поделиться",
      shareText: "Твоя ссылка для входа в «Ромчик | ИнфоМат»",
      reissue: "Перевыпустить",
      revoke: "Отозвать",
      revoked: "Приглашение отозвано",
      expires: (date: string) => `Действует до ${date}`,
      error: "Не получилось создать приглашение",
    },
    staff: {
      newStaff: "Новый сотрудник",
      listLoadError: "Не получилось загрузить сотрудников",
      empty: { title: "Сотрудников пока нет", text: "Добавь первого сотрудника" },
      roles: { owner: "Владелец", manager: "Менеджер" },
      showArchived: "Показывать архивных",
      archivedBadge: "В архиве",
      invitePending: "Приглашение не принято",
      actions: { invite: "Приглашение", archive: "Архивировать", edit: "Изменить" },
      archiveTitle: (name: string) => `Архивировать ${name}?`,
      archiveText: "Вход будет закрыт, данные сохранятся",
      archiveConfirm: "Архивировать",
      form: {
        createTitle: "Новый сотрудник",
        editTitle: "Изменить сотрудника",
        name: "Имя",
        role: "Роль",
        timezone: "Часовой пояс",
        submitCreate: "Создать",
        submitEdit: "Сохранить",
        nameRequired: "Введи имя",
        nameTooLong: "Не длиннее 150 символов",
      },
    },
  },
  /** Статус-бейджи — единственная таблица текстов (docs/07 §6.6) */
  status: {
    "lesson.scheduled": "Запланирован",
    "lesson.completed": "Проведён",
    "lesson.cancelled": "Отменён",
    "homework.assigned": "Выдано",
    "homework.submitted": "На проверке",
    "homework.needs_revision": "На доработку",
    "homework.graded": "Проверено",
    "homework.expired": "Сгорело",
    "homework.overdue": "Просрочено",
    "attendance.pending": "Не отмечено",
    "attendance.attended": "Был",
    "attendance.no_show": "Не пришёл",
    "attendance.cancelled": "Отменено",
    "bot.blocked": "Бот заблокирован",
  },
  /** Сообщения интерфейса (docs/07 §8.2) */
  messages: {
    saved: "Сохранено",
    networkError: "Нет соединения. Проверь интернет и повтори",
    offlineBanner: "Нет соединения. Проверим ещё раз",
    serverError: "Что-то пошло не так. Попробуй ещё раз",
    noAccess: "Эта страница недоступна",
    archiveConfirm: "Архивировать ученика? Данные и статистика сохранятся",
    invitationCreated: "Ссылка создана. Действует 7 дней, откроется один раз",
  },
  errors: {
    unknown: "Что-то пошло не так. Попробуй позже.",
    network: "Нет связи с сервером. Проверь интернет и попробуй ещё раз.",
    unauthenticated: "Не удалось войти. Открой приложение через бота или войди по ссылке из бота.",
    permission_denied: "Недостаточно прав для этого действия.",
    not_found: "Не найдено.",
    validation_error: "Проверь введённые данные.",
    rate_limited: "Слишком много запросов. Подожди минуту и попробуй снова.",
    homework_not_found: "ДЗ не найдено.",
    assignment_not_found: "Выдача не найдена.",
    assignment_not_gradable: "Эту работу сейчас нельзя оценить: она ещё не сдана.",
    assignment_not_returnable: "Вернуть на доработку можно только сданную работу.",
    assignment_not_extendable: "У этой выдачи срок перенести нельзя.",
    assignment_not_editable: "Работа уже сдана, файлы менять нельзя.",
    homework_extension_limit: "Срок уже переносили два раза. Больше нельзя.",
    no_next_lesson: "Следующего занятия нет. Выбери срок вручную.",
    score_out_of_range: "Балл выходит за пределы от 0 до максимума.",
    due_in_past: "Срок должен быть в будущем.",
    due_not_later: "Новый срок должен быть позже текущего.",
    due_at_required: "Укажи срок.",
    exam_type_required: "Для пробника выбери тип экзамена.",
    unknown_exam_type: "Неизвестный тип экзамена.",
    unknown_lesson: "Занятие не найдено.",
    subject_mismatch: "Предмет не совпадает с предметом экзамена.",
    file_not_found: "Файл не найден.",
    file_too_large: "Файл больше 10 МБ.",
    unsupported_file_type: "Подходят только jpg, png, heic и pdf.",
    empty_file: "Файл пустой.",
    login_link_invalid: "Ссылка недействительна или устарела. Попроси новую у Романа.",
    lesson_overlap: "В это время уже есть урок. Выберите другое время.",
    invalid_period: "Период указан неверно.",
    lesson_not_found: "Урок не найден.",
    lesson_not_scheduled: "Урок уже проведён или отменён: его нельзя изменить.",
    lesson_already_completed: "Урок уже отмечен как проведённый.",
    marks_mismatch: "Отметьте всех участников урока.",
    not_participant: "Этот ученик не участвует в уроке.",
    student_archived: "Ученик в архиве: добавить его на урок нельзя.",
    student_not_found: "Ученик не найден.",
    unknown_subject: "Неизвестный предмет.",
    invalid_teacher: "Урок может вести только активный сотрудник.",
    template_not_found: "Шаблон не найден.",
    last_owner: "Нельзя понизить или архивировать последнего владельца.",
    invite_already_used: "Ссылка уже использована. Попроси новую у Романа.",
    internal_error: "Произошла внутренняя ошибка. Попробуй позже.",
    mock_exam_not_found: "Результат пробника не найден.",
    mock_exam_linked_to_homework: "Результат создан из ДЗ: исправь оценку работы, и он обновится.",
    geometry_not_applicable: "Баллы по геометрии указываются только для ОГЭ математики.",
    geometry_too_big: "Баллы по геометрии не могут быть больше первичного балла.",
    exam_type_not_found: "Тип экзамена не найден.",
  },
} as const;

/** Ключи кодов ошибок, для которых есть понятный текст (см. docs/08 §1). */
export type ErrorTextKey = keyof typeof texts.errors;

/**
 * Формы множественного числа (docs/12 §10.2): plural(2, ["урок", "урока", "уроков"]) → "урока".
 * Русские правила: 1 → f1; 2–4 (кроме 12–14) → f2; иначе f3.
 */
export function plural(count: number, forms: readonly [string, string, string]): string {
  const n = Math.abs(count) % 100;
  const one = n % 10;
  if (n >= 11 && n <= 14) return forms[2];
  if (one === 1) return forms[0];
  if (one >= 2 && one <= 4) return forms[1];
  return forms[2];
}
